.git
.gitignore
.next
.vinext
.wrangler
coverage
dist
node_modules
out
outputs
work
deploy/nginx/cert
deploy/nginx/log

.env
.env.*
!.env.example

*.log
*.md
Dockerfile*
docker-compose*.yml
docker-compose*.yaml
